name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"

      - name: Set Yarn Berry (v4)
        run: corepack enable && yarn set version berry

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build
        env:
          GITHUB_PAGES: "true"

      - name: Prepare gh-pages folder
        run: |
          rm -rf gh-pages
          mkdir gh-pages
          cp -r demo/* gh-pages/
          cp -r dist gh-pages/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages
